title: Blog Personal
description: "Blog Personal"
author:
  name: "Miguel José Parra Sojo"
  email: "ingparrasojo@gmail.com"
  url: "https://parramiguel.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "MIJO"
year : "2022"
